### ISSUE TITLE
[Feature request] Remember main window size on program reopen

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#10]
Not a big deal, still would be good usability improvement :smiley: 

For example myself as big monitor owner always resize for some specific size (which is not as big as maximized, but still big enough to fit all cols in one view)

**Comment by Goli4thus** [comment]
Yeah makes sense. Added in 87c2acb.

**Comment by keybreak** [comment]
Works like charm, thanks! :+1: 

One minor thing:
![DeepinScreenshot_select-area_20200221220319](https://user-images.githubusercontent.com/47599989/75064053-41740800-54f7-11ea-97f6-f96216c942b2.png)

That's current default size when there are no **manager.conf** (previously it was little bigger and i think better for default representation)

**Comment by Goli4thus** [comment]
Ah, missed setting sane defaults. Thanks! Fixed in b31481a.

**Comment by keybreak** [comment]
Cool :smiley:
