### ISSUE TITLE
List update issue on conflict status + remove function

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#11]
I was messing around with some plugins in VM and came across this small issue (don't have time right now to check if it's repeatable, but something tells me it is):
1. I previously had some plugins which i've removed physically and they had status **NoBridge** in list

2. I've installed another versions of those same plugins to some other path and then added them to the list (hence name conflict was suggested)

3. I've decided to remove older versions from list, those with **NoBridge** status so switched to NoBridge filter to the right and had removed them with **Remove VST** function

4. After that they've been removed from list, but those who get conflict still had **Conflict** status wherever i do (i've tried resetting filtered etc)

5. After saving and rebooting program - it have been updated fine

Preferably list should be refreshed and **Conflict** status should be resolved in such case in runtime...

**Comment by Goli4thus** [comment]
I think I found the issue and made an update (9125f08).
Furthermore: "Blacklisted" VSTs no longer contribute to "Conflict" detection. (beforehand they did in some cases, some others not; so it was inconsistent).

**Comment by keybreak** [comment]
>  Furthermore: "Blacklisted" VSTs no longer contribute to "Conflict" detection. (beforehand they did in some cases, some others not; so it was inconsistent).

Makes sense! :+1: 

> I think I found the issue and made an update (9125f08).

Specifically that, meaning **Conflict** status update was fixed, but i've noticed something new (probably connected):

1. When i was testing that i've used Remove function (so should be No_So), but there was **Mismatch** status (i've checked folder - there was only .dlls)...Well i did update and then filter on the right shown exactly same quantity moved from **Mismatch** to **No_So** (i've checked folder - there were so's) and more than that - if you use filter there will be shown those 15 plugins but none of them inside this **No_So** filter list they're actually in **Disabled**, but filter to the right shows 0 in **Disabled**...So it's a mess now with right filter bar quantity update under some specific conditions :disappointed_relieved:  After program reboot list sorts itself out and acts normal, so it's only live update problem

2. I had crash of whole program inside scan window (can't remember exact sequence, as it was very unexpected and i was acting fast, but i think it was between adding folder and pressing the scan button where there's some OK dialog), i was unable to repeat it so far so no idea how to debug...

**Comment by Goli4thus** [comment]
> Specifically that, meaning **Conflict** status update was fixed, but i've noticed something new (probably connected):
> 
>     1. When i was testing that i've used Remove function (so should be No_So), but there was **Mismatch** status (i've checked folder - there was only .dlls)...Well i did update and then filter on the right shown exactly same quantity moved from **Mismatch** to **No_So** (i've checked folder - there were so's) and more than that - if you use filter there will be shown those 15 plugins but none of them inside this **No_So** filter list they're actually in **Disabled**, but filter to the right shows 0 in **Disabled**...So it's a mess now with right filter bar quantity update under some specific conditions disappointed_relieved  After program reboot list sorts itself out and acts normal, so it's only live update problem
> 

There certainly was a missing sidebar update event in regards to performing an "update" action.
I've added that in e99fc6d.
Apart from that I'm not sure if this fully covers your description. Maybe try the same thing with that update.

>     2. I had crash of whole program inside scan window (can't remember exact sequence, as it was very unexpected and i was acting fast, but i think it was between adding folder and pressing the scan button where there's some OK dialog), i was unable to repeat it so far so no idea how to debug...

Well, it's not reproducable, then it's pretty hard to judge.

**Comment by keybreak** [comment]
> There certainly was a missing sidebar update event in regards to performing an "update" action.
I've added that in e99fc6d.
Apart from that I'm not sure if this fully covers your description. Maybe try the same thing with that update.

I believe that commit fixed those problems, at least from making same thing, i'll keep my eye on it though :+1: 

> Well, it's not reproducable, then it's pretty hard to judge.

Yeah that's pity...If i'll encounter that, any chance to catch reason outside of compiling with debug and monitor terminal output?

**Comment by Goli4thus** [comment]
> Yeah that's pity...If i'll encounter that, any chance to catch reason outside of compiling with debug and monitor terminal output?

Well, that might be a start. If it's a segfault or something, then there should be a message on terminal at least.
