### ISSUE TITLE
Scan window type tooltip needs update

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#12]
Tooltips for VST type are misleading now, seems you forgot to update it with our latest changes :smiley: 

![image](https://user-images.githubusercontent.com/47599989/75140703-81f2a200-5700-11ea-9f8c-d4258aaddb0b.png)

**Comment by Goli4thus** [comment]
Ah, that one was always like that. But yeah, doesn't really make sense.
I've removed the tooltip at item level and updated table header tooltips overall (ca07ba2).
