### ISSUE TITLE
Situation where orphaned links may lead to some workflow questions

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#13]
Pretty funky and complex situation, i must admit, yet still may happen and raise some questions... :smiley: 

1. Remove plugin from previous location (by Wine or manually)
2. Install / copy same plugin to other location
3. Open linvstmanager, on orphans detected notification - choose to **not** remove them
4. Remove orphaned plugin by selecting it and using **Remove VST** function
5. Add plugin (installed to that new location) with any method available to **linvstmanager**
6. It will correctly get **No_So** status - use **Update** function
7. It will correctly get **Disabled** status - try to use **Enable** function

You can't enable those anyhow, until physically removing those broken orphaned link from link folder...

I suggest little improvement for **Enable** function in case it's used on same name as broken orphaned link:
1. Force remove such broken link
2. Create new one as usual

**Comment by Goli4thus** [comment]
Ok, I was able to reproduce it.
The issue was actually with the remove operation, because it didn't handle removing a link without a target properly. Fixed in c586a16.

**Comment by keybreak** [comment]
Tested fix - works good :+1:
