### ISSUE TITLE
Any chance you could make this work with slightly older QT / Ubuntu LTS?

### ISSUE THREAD

**Issue by oneillkza** [Goli4thus/linvstmanager#15]
Hi,

When I try to compile, it throws a bunch of errors that look like this:

```
[ 44%] Building CXX object CMakeFiles/linvstmanager.dir/src/main.cpp.o
/home/kieran/Downloads/linvstmanager-1.0.1/src/linkhandler.cpp: In member function ‘RvLinkHandler LinkHandler::refreshStatus(bool, int, bool, bool)’:
/home/kieran/Downloads/linvstmanager-1.0.1/src/linkhandler.cpp:58:56: error: ‘class QString’ has no member named ‘chopped’; did you mean ‘chop’?
                         filePathSo = vstBucket.vstPath.chopped(3) + "so"; // Replace "dll"
                                                        ^~~~~~~
                                                        chop
```

Some Googling suggests that this is due to a dependency on QT5.10:

https://phabricator.kde.org/T8526

I'm running Ubuntu 18.04, which is the current latest LTS version, but that only has this when running the apt command suggested in the docs for linvstmanager:

```
qt5-default is already the newest version (5.9.5+dfsg-0ubuntu2.5).
```

Could you please either update the instructions, or tweak linvstmanager so it's not dependent on the newer version?

**Comment by niowniow** [comment]
I'm facing the same issues and installing qt is a pain... (requiring accounts, not detecting the correct versions,...).
Maybe a binary release of linvstmanager could solve this issue for new users.

**Comment by keybreak** [comment]
@Goli4thus 
That's what i was referring to as my worry though :laughing: 

Probably best option would be to pack some of those Flatpak / Snap / AppImage on release, that would help old qt distros...While at the same time keep your sanity

**Comment by Goli4thus** [comment]
Thanks for letting me know about this. I will try to have a look later today.
But in general: If it's only about that one API call 'chopped', then I'd rather forego using it and make it work for QT 5.9.
Overall though I will try to avoid going too far back with QT versions.
But the latest Ubuntu LTS seems reasonable in this case.

**Comment by Goli4thus** [comment]
Ok, took some time due to having to setup a Ubuntu 18.04 VM, but it's looking good now.
Compiled and installed fine for me with this change: 76412c0.

Maybe you can give it another try with the latest master version (git clone ..., etc.).
If it's wokring fine for you I might make another release soon.

**Comment by niowniow** [comment]
Perfect! Compiles without any issue on my machine with Ubuntu 18.04. Thanks a lot.

**Comment by keybreak** [comment]
Aaaand still works same for me :smile: 
Should be safe to release

**Comment by Goli4thus** [comment]
Thank you both for giving it a test ride!
Release is coming up.

**Comment by oneillkza** [comment]
Works for me too! Thanks for such a quick response.
