### ISSUE TITLE
Aur seems gone

### ISSUE THREAD

**Issue by perlindgren** [Goli4thus/linvstmanager#16]
It seems that the aur for arch is gone...

**Comment by Goli4thus** [comment]
Seems like it, yeah.
So far a user named "usrmusicman" was nice enough to have created and maintained that one as well as all four linvst bridges.
Don't really know why they are all gone all of a sudden.

I noticed I myself never installed linvstmanager using the AUR though.
Therefore I actually don't have access to the PKGBUILD.

Could you maybe have a look, if it's still lying around on your system?
In case you're using _yay_ as an AUR helper, it should be located in `~/.cache/yay/linvstmanager/PKGBUILD`.

EDIT:
Nevermind, just noticed he has a git repo: https://github.com/usrmusicman/ArchBuilds/blob/master/linvstmanager/PKGBUILD

So maybe you could create an issue on his github. It might just be that his packages got removed from AUR for whatever reason.

**Comment by perlindgren** [comment]
```
# Maintainer Alex Mcmillan <linuxguy93@gmail.com>

pkgname=linvstmanager
pkgver=1.0.2
pkgrel=2
pkgdesc="GUI Manager for the Linux VST Bridge (LinVST)"
arch=('x86_64')
url="https://github.com/Goli4thus/linvstmanager"
groups=('pro-audio')
depends=('qt5-base')
makedepends=('cmake')
optdepends=('linvst2: Windows VST2 to Linux VST bridge'
            'linvst3: Windows VST3 to Linux VST bridge')
source=("https://github.com/Goli4thus/linvstmanager/archive/v${pkgver}.tar.gz")
sha256sums=('8e6c247a06802c41d84848d7ad910961e7f5a7ab0622be2d6716121401aa0051')

build() {
	cd $srcdir/$pkgname-$pkgver
	mkdir -p build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX=/usr ..
	make -j$(nproc) DESTDIR=${pkgdir}
}

package() {
	cd $srcdir/$pkgname-$pkgver/build
	make -j$(nproc) DESTDIR=${pkgdir} install
}
```

**Comment by Goli4thus** [comment]
Thanks for posting it! But as I said, the original maintainer might just not be aware that his packages got removed. So I'd suggest to contact him first (see edit above) by creating an issue on his github.

**Comment by keybreak** [comment]
That's the problem with AUR, if it's not maintained by someone both willing to be on top of updates & reliable... :thinking:

**Comment by Goli4thus** [comment]
> That's the problem with AUR, if it's not maintained by someone both willing to be on top of updates & reliable... thinking

Nah, in this case I really think it might just be some misunderstanding and he might not be aware of them being gone. It's not like he deleted them from his github like he did with the "-X" linvst bridges [a while back](https://github.com/usrmusicman/ArchBuilds/commit/a0603f8dd1205f0793051446eadcb87a74e8a58f).

Anyway: I've created an issue [here](https://github.com/usrmusicman/ArchBuilds/issues/1).

**Comment by Goli4thus** [comment]
So I got a reply and it seems it was a concious decision on this part after all. He prefers to maintain PKGBUILDs on github now.

I've added a link to the respective one for LinvstManager (a5217386b35462b3963afce9f5ffae257ee3ec14).
Guess we'll have to see if people make use of it. 
If all fails, the _manual install_ isn't too bad imo. But that might just be me... :thinking:

**Comment by madskjeldgaard** [comment]
> So I got a reply and it seems it was a concious decision on this part after all. He prefers to maintain PKGBUILDs on github now.
> 
> I've added a link to the respective one for LinvstManager ([a521738](https://github.com/Goli4thus/linvstmanager/commit/a5217386b35462b3963afce9f5ffae257ee3ec14)).
> Guess we'll have to see if people make use of it.
> If all fails, the _manual install_ isn't too bad imo. But that might just be me... thinking

Very bizarre IMO. I just discovered today that this had happened. I installed it before they were pulled and wondered why I couldn't find it anymore.
