### ISSUE TITLE
Fix PayPal link on README.md

### ISSUE THREAD

**Issue by tetebueno** [Goli4thus/linvstmanager#17]
It redirects to (resulting in a 404):
```
https://github.com/Goli4thus/linvstmanager/blob/master/paypal.me/donate2goli4thus
```
Instead of:
```
https://paypal.me/donate2goli4thus
```
Your project is too cool to miss any donation :D

Cheers.

**Comment by Goli4thus** [comment]
Thanks for letting me know! Turns out the "https://" part was missing. It's fixed now (fee9d245b744725d06d1de64d64aea36212252d4).
And thanks for the donation! :relaxed:
