### ISSUE TITLE
Low rez icon in some scenarios

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#21]
![Screenshot_20200726_194120](https://user-images.githubusercontent.com/47599989/88485502-d97e8d80-cf7e-11ea-9f64-47d043115086.png)

Sorry. best i can to catch this on screenshot, point is unlike other icons for some reason linvstmanager is pixelated here in KDE...
This is "Large icon" task switcher...

I have no idea why it happens, since we already made all possible sizes...

P.S. I rebooted after install (aka update icon cache)

**Comment by Goli4thus** [comment]
Hmm, only thing I can think of is that even though we made all sizes up to 1024, they are all installed into _/usr/loca/share/icons/**hicolor**/..._.
Do you maybe have some other icon pack selected in settings?
But as I understand it, _hicolor_ is the fallback icon theme (according to [this](https://askubuntu.com/questions/300126/what-is-special-about-the-hicolor-icon-theme)). So I'd assume they;d be picked up in any case by the system.

After some searching I think this is a "bug" in KDE after all.
See https://bugs.kde.org/show_bug.cgi?id=351055 .

Maybe try that workaround at the end: _"You have to set the .desktop file name in "Appearance & fixes" tab."_ (whatever that means; maybe you know that as a KDE user).
LinvstManager's desktop file is located in `/usr/local/share/applications/linvstmanager.desktop`.

**Comment by keybreak** [comment]
> After some searching I think this is a "bug" in KDE after all.
See https://bugs.kde.org/show_bug.cgi?id=351055 .

Damn, how the hell you found anything on their bugtracker?! :laughing: 
Thx, that's definitely the problem...
Dreaded KDE, i'm not happy with it either, but for now since i'm busy it's best easy-to-go option :+1: 

I'll wait for fix, thx again :smile:
