### ISSUE TITLE
linvstmanager is back on aur

### ISSUE THREAD

**Issue by madskjeldgaard** [Goli4thus/linvstmanager#23]
Hi! Just wanted to let you know that linvstmanager (and all the linvst bridges) are back on the AUR so that arch people may install it from there:

https://aur.archlinux.org/packages/linvstmanager-git/

Note, the package is now called `linvstmanager-git` :) 

to install:
`sudo pacman -S linvstmanager-git`

**Comment by Goli4thus** [comment]
Hey! First off: Thanks for putting it up on AUR, I'm sure people will find it helpful.
I've updated the README (7cf2a78191f4ac1eff2a97ab90cad2ef82fef402).

Two minor things:
1) Please consider adding the `make -j4` option (or similar) to allow the build to use more than one core during build (always nice for a user if the build takes less time).
2) As far as I know from an AUR user perspective, a _"-git"_ postfix usually means that the PKGBUILD references the master branch of the respective application. Looking at your PKGBUILD, it seems you are references the latest release though (which sure is the preferred choice for this). So it's rather about the naming. But I understand that we already had `linvstmanager` as a package before and you are trying to avoid conflicts for existing users (even though that old PKGBUILD no longer is on the AUR strictly speaking). So yeah, I don't know how you think about this, but it might be worth considering to exchange the _"-git"_ postfix for something else (e.g. _"-stable"_).


> to install:
> `sudo pacman -S linvstmanager-git`

Maybe I'm mistaken or you've configured pacman in some way to use an AUR helper on top, but usually one needs to use a dedicated AUR helper (e.g. `yay`) to install from AUR.

**Comment by keybreak** [comment]
@Goli4thus 
Btw, this days i've seen people compiling Kernel with:
```
make -j$(nproc)
```

Maybe it's already safe?
Not big deal for such small project, but you know...Handy for threadrippers out there :laughing:

**Comment by Goli4thus** [comment]
@keybreak ;)
Yeah that's certainly safe and probably the most flexible variant. 
One just needs to be aware that it will use all cores that way, so not a very "background install" if one wants to preserve some resources for other things. Well, but "-j4" would use all cores if 4 is all one has...

**Comment by madskjeldgaard** [comment]
> Hey! First off: Thanks for putting it up on AUR, I'm sure people will find it helpful.
> I've updated the README ([7cf2a78](https://github.com/Goli4thus/linvstmanager/commit/7cf2a78191f4ac1eff2a97ab90cad2ef82fef402)).
> 
> Two minor things:
> 
>     1. Please consider adding the `make -j4` option (or similar) to allow the build to use more than one core during build (always nice for a user if the build takes less time).
> 
>     2. As far as I know from an AUR user perspective, a _"-git"_ postfix usually means that the PKGBUILD references the master branch of the respective application. Looking at your PKGBUILD, it seems you are references the latest release though (which sure is the preferred choice for this). So it's rather about the naming. But I understand that we already had `linvstmanager` as a package before and you are trying to avoid conflicts for existing users (even though that old PKGBUILD no longer is on the AUR strictly speaking). So yeah, I don't know how you think about this, but it might be worth considering to exchange the _"-git"_ postfix for something else (e.g. _"-stable"_).
> 
> 
> > to install:
> > `sudo pacman -S linvstmanager-git`
> 
> Maybe I'm mistaken or you've configured pacman in some way to use an AUR helper on top, but usually one needs to use a dedicated AUR helper (e.g. `yay`) to install from AUR.

Thanks for the feedback!
I did actually use the j flag at first but as a person on AUR rightfully pointed out, it's not a good idea or necesarry because of the `makepkg.conf` config file on Arch where you set that stuff systemwide for all packages.

Oh yeah, and sorry, I was very tired when I wrote the issue above. It is correct, you need an aur helper to install. I use yay so `yay -S linvstmanager-git` and then it asks you nicely if you want to install all of the bridges :) 

and about 2: I think you are right. I'll have a think about how to do that.

**Comment by Goli4thus** [comment]
Ah, now that you're saying it, yeah, I've read about `makepkg.conf` in the past. Then it's fine as is.

Usability is always good to keep in mind, so it offering to install the bridges as well is a nice touch for sure.

**Comment by madskjeldgaard** [comment]
I forgot it too, but was gently reminded by a contributor :)

**Comment by Goli4thus** [comment]
Alright, just cleaning up issues and therefore closing this.
Feel free to re-open it if there's a need.

**Comment by madskjeldgaard** [comment]
Cool!
