### ISSUE TITLE
Symlinks naming

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#3]
## Solutions

> So the only idea I have now is:
> - no more path based suffix of any kind
> - still allow to add identically names VST.dll files to LinVstManager (differentiation is based on each VST's absolute path re it being unique)

Agree with both points

> - possibly highlight duplicate VST names (in name column) and allow user to rename only the internal name of tracked VSTs.

definitely, not possibly!
I think maybe give them some separate status even and / or at the very least keep duplicated names on top of list, so user would immedeately know that this is something to be sorted...

> Reason:
> This "name" that is shown in LinVstManager is derived from the base VST.dll filename.
> But after that it is only ever used to:
> - be displayed in the table
> - be the name of the *.so link created in the link folder.
> - So if we allow the user to rename VSTs within LinVstManager (not the actual source VST.dll), then a user could give a unique name himself and that new name would end up being the so-link in the link folder and therefore the name that a DAW picks up (if that DAW likes picking up the filename instead of the embedded name within the dll).

In summary:
- Inside wineprefix itself we must always keep NAME.dll = NAME.so
- In link folder we can rename .so symlinks however we want and it will still work

Is this correct?
If it is - that i agree!

> What do you think?
> Would this be sufficient solution?

If i understood you correctly - i think this is brilliant solution! :+1: 
________________

### Theory

> How do you currently get Renoise to load two VSTs with the same name of the dll file? Do you rename one of them intentionally?

I answered it directly in the middle of post https://github.com/Goli4thus/linvstmanager/issues/1#issuecomment-583844083 maybe missed the point of question, and you mean .so?
But it's same, basic idea - divide (by folder structure) and conquer! At least that what i had done with linvstmanage :smiley:

**Comment by Goli4thus** [comment]
First off: Thanks for creating new issues per topic. Much more managable!

> > * possibly highlight duplicate VST names (in name column) and allow user to rename only the internal name of tracked VSTs.
> 
> definitely, not possibly!
> I think maybe give them some separate status even and / or at the very least keep duplicated names on top of list, so user would immedeately know that this is something to be sorted...

I think we talked past each other on that one.
I meant only renaming the within _LinVstManager_ tracked name of the VST (only the name column one; not anything related to the real VST.dll or the VST.so file next to it).

> 
> > Reason:
> > This "name" that is shown in LinVstManager is derived from the base VST.dll filename.
> > But after that it is only ever used to:
> > 
> > * be displayed in the table
> > * be the name of the *.so link created in the link folder.
> > * So if we allow the user to rename VSTs within LinVstManager (not the actual source VST.dll), then a user could give a unique name himself and that new name would end up being the so-link in the link folder and therefore the name that a DAW picks up (if that DAW likes picking up the filename instead of the embedded name within the dll).
> 
> In summary:
> 
>     * Inside wineprefix itself we must always keep NAME.dll = NAME.so
> 
>     * In link folder we can rename .so symlinks however we want and it will still work
> 
> 
> Is this correct?
> If it is - that i agree!

Yes that's correct. I just tested it again myself.
I manually created a symlink to a bridged VST's *.so-file.
That symlink I named "TDR_MEGA_SUPER_NOVA" and both Reaper and Renoise loaded it just fine.
The only difference was that Reaper didn't care about that name and still showed me the actual VST name and vendor (which is embeded inside the VST.dll) and Renoise actually dispayed "TDR_MEGA_SUPER_NOVA" in its FX browser. But it still loaded/opened fine.


> 
> > What do you think?
> > Would this be sufficient solution?
> 
> If i understood you correctly - i think this is brilliant solution! +1

Yeah, this seems like the way to go then. 
A transparent solution for the average user that has no conflicting names.
A flexibile solution for those that need to resolve conflicting names.
And overall a portable solution, because whatever name the user chooses for a VST, it is being tracking inside the config xml of _LinVstManager_ and all one needs to fix up is the VST's absolute path, if that for whatever reason ever changes.

I'll try to implement that soon.

**Comment by Goli4thus** [comment]
Alright, conflict and rename support has been added (e3af3a96e3c98b0efbb82004445d183bb49de6f5).
Additionally I've added a sidebar (de558b2e6400d6ef0fe0369ebb17fb362718bb55) that should help in managing lots of VSTs (hint: those colored boxes in the sidebar are buttons and clicking them will fill the filterbar).

**Comment by keybreak** [comment]
Thanks! Will test and get back to you :smile:

**Comment by keybreak** [comment]
First of all - that is brilliant solution!
Really good thinking man! :+1: 

And works really good, i have tested the crap out of it and couldn't find any serious flaw + sidebar rules!

__________

One minor status update issue again :smile: 

1. Add couple of same names vsts
2. Rename one who reports status as **Conflict**
3. After rename status will still be **Conflict**, although should be **No_So** or **Disabled** (depending on case)


Just as previously - after reboot status is fixed, it's just a matter of status update after rename action

__________

Also i think from UX point of view, that would make sense to use sidebar filter color boxes react as checkbox, meaning toggle between filter / not filter states.

Because sometimes you just want to quickly check something and then go back to full list, now to do that you need to move mouse and close filter in the bottom of program (well of course you can Ctrl+F as advanced user too, but you know :laughing: ).

**Comment by Goli4thus** [comment]
> First of all - that is brilliant solution!
> Really good thinking man! +1
> 
> And works really good, i have tested the crap out of it and couldn't find any serious flaw + sidebar rules!
Nice to hear! I'm glad we've found a solution that works for various use cases.

> 
> One minor status update issue again smile
> 
>     1. Add couple of same names vsts
> 
>     2. Rename one who reports status as **Conflict**
> 
>     3. After rename status will still be **Conflict**, although should be **No_So** or **Disabled** (depending on case)
> 
> 
> Just as previously - after reboot status is fixed, it's just a matter of status update after rename action
>
Yeah, that was a bug. Thanks for the explanation. Fixed in a0113a7.
 
> Also i think from UX point of view, that would make sense to use sidebar filter color boxes react as checkbox, meaning toggle between filter / not filter states.
> 
> Because sometimes you just want to quickly check something and then go back to full list, now to do that you need to move mouse and close filter in the bottom of program (well of course you can Ctrl+F as advanced user too, but you know laughing ).

Good idea. Added in 116004e.

**Comment by keybreak** [comment]
Tested both patches - works great! :+1: 

_____

Quick question before closing, i've noticed that you started to use **softlinks** instead of **symlinks**:
https://github.com/Goli4thus/linvstmanager/commit/0b46555b3faf9f837fd4b6e8590d058a005c5775

I'm not educated on the matter completely, but remember reading somewhere that there are some important differences...Can you expand on that? Won't it hurt us compared to symlink solution?

P.S. I really love **Orphans detected** on start and Selection section on bottom of status filters - you're my personal Jesus! :smile:

**Comment by Goli4thus** [comment]
> Tested both patches - works great! +1

Good to hear, thanks for testing!

> 
> Quick question before closing, i've noticed that you started to use **softlinks** instead of **symlinks**:
> [0b46555](https://github.com/Goli4thus/linvstmanager/commit/0b46555b3faf9f837fd4b6e8590d058a005c5775)
> 
> I'm not educated on the matter completely, but remember reading somewhere that there are some important differences...Can you expand on that? Won't it hurt us compared to symlink solution?
> 

I actually haven't changed anything about the behavior code wise re making those "links".
For linux at least there are two kinds of links
1) Hard links
2) Symbolic links (also called symlink or softlink)

Symlinks you get with command `ln -s [link source] [link destination]`.
Hardlinks without the "-s".

A symlink also just "point" to its target, whereas a hardlink can be considered the same file.
(here's more info: https://linoxide.com/linux-how-to/difference-soft-link-hard-link/)

As a test I've changed into an empty folder, created an empty file called _source.txt_ and did run the following commands:
`ln source.txt link_hard.txt`
`ln -s source.txt link_soft.txt`

Then looking at the result:
```
$ ls -l
total 0
-rw-r--r-- 2 goli goli  0 12. Feb 22:49 link_hard.txt
lrwxrwxrwx 1 goli goli 10 12. Feb 22:50 link_soft.txt -> source.txt
-rw-r--r-- 2 goli goli  0 12. Feb 22:49 source.txt
```

You can for instance change into the _link folder_ and run `ls -l`. You'll see that all those symlinks point to the actual VST location (specifically the ".so" file next to a VST).

And regarding the actual naming:
I think a long time ago I learned about it under the name of "softlink". But I also use "symlink". It's the same thing when talking about it in a linux context. Yeah, it's confusing, but I think I've used mostly "softlink" in comments in the code and the README (probably not always).

> P.S. I really love **Orphans detected** on start and Selection section on bottom of status filters - you're my personal Jesus! smile

Ha, thanks for noticing those things! :+1: 
They aren't the most obvious but actually add up to the whole experience.
To be honest, I'm a big usability fan. I like programs that allow for an efficient workflow, stuff like shortcuts, well thought out menu layouts, the right information at the right time, and so on.

**Comment by keybreak** [comment]
Thanks for proper explanation, skill learned :smiley: 

> Ha, thanks for noticing those things! :+1: 
They aren't the most obvious but actually add up to the whole experience.
To be honest, I'm a big usability fan. I like programs that allow for an efficient workflow, stuff like shortcuts, well thought out menu layouts, the right information at the right time, and so on.

Well...That's my blessing & curse - i see those things when they are there and especially when they're not!

I'm designer in UI / UX myself, and extremely perfectionist person.

You have done an excellent job from top to bottom with **linvstmanage** and **linvstmanager**, it is a quality well thought out work and i'm not sure that i would be that enthusiastic about LinVST itself and all those insane amounts of tests https://github.com/keybreak/linux-vst-compatibility-list without your contribution!

I wish that all the programs and DEs on Linux was that thought out...Sadly it's still long road, every DE needs sh*tload of work / patches / scripting and configuration to make it bearable for me, now i'm for example want to try switch for KDE which obviously needs insane amount of work for it to be actually good at least in most aspects of UI / animations / sane settings...Already 3000 lines of bash script :laughing: 

Still i have a feeling that for something to be perfect enough i'd have to go TTY road in the end and start to live in a cave :rofl:

**Comment by Goli4thus** [comment]
Yeah, I can relate to perfectionism being a true blessing in disguise.

Wow, thanks for the compliments! Really didn't know those tools could end up being that helpful. And I can't even phantom on how much time all that testing must have taken nontheless.

Anyway, you sure planted some thoughts in my head back then when mentioning a scan feature in linvstmanage.

I actually gave it a real thought back then but soon realized that it's just not doable with that barebones console UI and simple INI config file. At least not if doing it "right" was of priority. So it became pretty obvious that a real GUI app is needed.

There sure is beauty in simplicity.

**Comment by keybreak** [comment]
> Really didn't know those tools could end up being that helpful.
> Anyway, you sure planted some thoughts in my head back then when mentioning a scan feature in linvstmanage.

That's how it always works, we bounce of each other and improve, you've sparked me -> i've sparked you -> while testing i've sparked osxmidi to fix about 10 critical bugs in LinVST (which are essential for compatibility and actual production use) -> you've created **linvstmanager** which i'm sure once i'll finish with what i have in mind will play a key role in accessibility for a lot of people for more testing and potentially contribution to all of our projects & hopefully to complete Wine's **d2d1.dll**!

> And I can't even phantom on how much time all that testing must have taken nontheless.

There's still a lot of work (sadly i had to pause that for a while), according to Renoise cache there's 841 left to test, in reality should be a little less...After i finish my own quest and formalize it a little better:
- I want to open user section and make that public so that anyone can add to db by following proper testing criteria

- Make accessible guide of all the advantages of using Linux + Wine + LinVST + linvstmanager (and there are a lot) to show more and more people no need to be slaves of Windows / Apple and suffer from a lot of disadvantages of those approaches. It's one thing to go free / open source and simple, and another to hold a studio where "industry standards" and full compatibility do matter a lot, now in music i believe Linux is fully ready for serious work, unlike for example Raster / Vector graphic fields, sure there are some native tools and ability to use :skull_and_crossbones:  Photoshop CC 2019 under Wine, but it's far behind what could be considered reliable / fully featured stil.

> So it became pretty obvious that a real GUI app is needed.

There shouldn't be too much problems i guess...
As far as i understood it's all written on C++ with QT5 as UI, if you don't use some voodoo magic imports and stick to basics should be all around compatible.

One potential downside i see though:
- I guess you'd need to support QT at least to some capacity, meaning for example QT5 -> QT6 period Arch / Manjaro would fire QT6 immediately (but as far as i know QT5 won't get dropped for a long time still), yet something like Debian / Ubuntu would lag behind by using QT5...I don't know much about it, but seems that it would need a little more maintenance compared to python script
