### ISSUE TITLE
[Suggestion] List sort order

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#4]
Since now default sort mode is by Name, and it works like that:
```
+
.
#
A
B
C
a
b
c
```
I think perhaps more natural and logical for human readability sorting by name would be:
```
+
.
#
A
a
B
b
C
c
```

**Comment by Goli4thus** [comment]
Yeah why not. Added with f440ead.

**Comment by keybreak** [comment]
Cool, it works :+1:
