### ISSUE TITLE
Manjaro required packages little overkill

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#6]
As far as i see **gcc-multilib** is overkill (or maybe i missed something)
```
sudo pacman -S cmake make gcc git wine qt5-base gcc-multilib
```

If you run **pacman -Qi gcc**, it says that it both provides and replaces **gcc-multilib**, so just **gcc** should be enough?

**Comment by Goli4thus** [comment]
After having a look at `pacman -Qi gcc` is actually seems so. 
Furthermore it specifically mentions that it `Replaces: gcc-multilib`.
And sure enough, I don't even have `gcc-multilib` installed on my PC.
So it really seems Manjaro already includes it in `gcc` package.

Thanks for mentioning it. I've removed it from the README.
