### ISSUE TITLE
question about airwave

### ISSUE THREAD

**Issue by dreamcat4** [Goli4thus/linvstmanager#7]
So is it possible to make airwave another supported vst bridge? I understand that airwave includes a gui manager app too. however it would be nice to include it here since some vst plugin dont work well with linvst and bitwig daw specifically i found this occur yesterday witth bc free amp. Therefore some of my plugin may not be possible with linvst due to that interop issue with that particular daw. Thanks for considering this matter.

**Comment by Goli4thus** [comment]
To be honest that is not the aim of this project. This application is about providing a GUI manager specifically for various LinVst flavours that are all handled similiarly. A usability improvement so to say.
I personally have no real experience with airwave and don't want to make this project needlessly complicated by attempting to handle all the bridges there currently exist.

**Comment by keybreak** [comment]
While i agree that this would be nice addition perhaps (as while my testing of LinVST i have found some things that Airwave have done and LinVST can not, in most cases that was matter of fixing LinVST)...

In general LinVST seems like far more superior option, with exception of very few rare edge-cases.

There should be something specific about Bitwig (like sometimes it was with Renoise until it got fixed) and better (but harder) approach would be to debug LinVST with osxmidi and try to fix this things...

**Comment by dreamcat4** [comment]
Thank you for these feedback. And it's a great comments there @keybreak in regards to this matters with Bitwig specifically. Which can be very much more difficult client / host of wine VSTs than the other DAWs.

My current strategy ATM is to just try to make use of both tools. I have not decided upon a favorite tool yet for Bitwig. Will be trying more plugins going forwards and perhaps the situation will become more clear as to which one is fitting better for bitwig. Also as time moves forward, both linvst and airwave will continue to be updated / bugs fixed... We shall see!

**Comment by keybreak** [comment]
> Also as time moves forward, both linvst and airwave will continue to be updated / bugs fixed... We shall see!

Wow, i was surprised to see there is first small commit in Airwave for 4 years - that's a good sign, i though it's dead-end with that project :smiley:

**Comment by dreamcat4** [comment]
Ah i see now.. thanks for mentioning that. Looking again there seems to be a couple of other forks so at least there still something going on. Less than linvst.

https://github.com/psycha0s/airwave/network
