### ISSUE TITLE
[Improvement] Ease of install suggesstion

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanager#8]
**Install.sh**
```
#!/bin/sh

mkdir build && cd build
cmake ..
make -j4
sudo make install

```

Because...Why not? :smiley: 
This way it's 1 click / 1 command and no need to update README section in case anything will change :smile: 

Win-Win i think!

**Comment by Goli4thus** [comment]
There's a reason those things are not combined in one go.
Usually one wants to see the result of each step. Especially when there is comething like a _configure_ step involved before make (which we don't have).

But also consider this:
Let's say a user has a dependency problem during `make`.
Let's say he resolves it and want's to try to build again.
If he runs your script then it all starts over from start.
If he just runs `make -j4`, it picks up where the problem previously was and only the remaining steps of the build need to be done.

Furthermore mixing `sudo` commands into a script with other "non sudo" commands is not that great of a thing.

So I'd say not to this one.

**Comment by keybreak** [comment]
Well, maybe you right then, just thinking out loud...

> Furthermore mixing sudo commands into a script with other "non sudo" commands is not that great of a thing.

Why though?

___________

Maybe divide build & install steps like that with question :smiley: 

```
#!/bin/sh

mkdir build && cd build

echo "Build"
echo

echo "cmake .."
echo
cmake ..
echo

echo "make -j4"
echo
make -j4
echo

local input
while true;
do
    echo
    read -r -p "Install? [Y/n] " input
    echo

    case $input in
        [yY] )
            echo "sudo make install"
            sudo make install
            break
        ;;
        [nN] )
            echo "Skip installation"
            break
        ;;
        *) echo "Wrong option" ;;
    esac
done

```

**Comment by Goli4thus** [comment]
> Well, maybe you right then, just thinking out loud...
> 
> > Furthermore mixing sudo commands into a script with other "non sudo" commands is not that great of a thing.
> 
> Why though?

Imagine it would be a longer script with multiple sudo commands mixed in.
I remember certain distributions have setup sudo so the password is remembered for like a minute or 5 minutes after entering it, so a user doesn't have to re-type it every time.
So if an average user downloads such a script and enters his password the first time the script wants to run a sudo command, he will enter it.
But because the password is remembered, it will run subsequent sudo commands just fine without having to ask the user.

So the user might not even know that he executed a bunch of commands with sudo.

So it's certainly an "awareness" thing for the average user.

> 
> Maybe divide build & install steps like that with question smiley
> 

I see you're putting some thoughts into this, so I try as well:

> ```
> #!/bin/sh
> 
> mkdir build && cd build
> ```
What if the script doesn't work the first time the average user runs it?
What if he needs to resolve some conflicts and run it again.
With that line above he will no longer be in the directory where the script is located and might be confused.

Basically when writing a script that's not only for personal user, one always has to remember that there are less advanced users and that there's not only the "good case" where everything works first try. A script should always have some safety checks in place to catch "bad cases".

> 
> echo "Build"
> echo
> 
> echo "cmake .."
> echo
> cmake ..
> echo
> 
> echo "make -j4"
> echo
> make -j4
> echo
> 
> local input
> while true;
> do
>     echo
>     read -r -p "Install? [Y/n] " input
>     echo
> 
>     case $input in
>         [yY] )
>             echo "sudo make install"
>             sudo make install
>             break
>         ;;
>         [nN] )
>             echo "Skip installation"
>             break
>         ;;
>         *) echo "Wrong option" ;;
>     esac
> done
> ```

The rest probably works like that, but I still wouldn't advertise it for _LinVstManager_.
Why?
Because I really see value in bringing the average user into contact with something like build instructions. Especially when it's just a couple commands.
Commands the average user will most certainly encounter again and again when trying to install software from source.
If every open source app makes a custom build script, then it gets maximally confusing really fast. But if most apps use basically the same commands (depending on coding language), rather sooner than later the average user will see a pattern and will be able to apply what he has learned at a future point in time.

If we really want to automate the install, then creating distribution packes would be the actual solution, but that's a whole another challange that's way out of question for now.

**Comment by keybreak** [comment]
> So it's certainly an "awareness" thing for the average user.

Oh ok, that makes sense...I guess i just used to do personal scripts this way...
And also considering the fact that i will never run script without at least quickly looking it's code :laughing: 

> What if the script doesn't work the first time the average user runs it?

Well, there will be errors \ warnings and user still will have chance to not install script before actually installing software in system, should be at least about the same as running those commands manually?

>  What if he needs to resolve some conflicts and run it again.

Close script, investigate, just as running those commands manually :smiley: 

>  With that line above he will no longer be in the directory where the script is located and might be confused.

I'm really glad that you've asked & noticed that one, especially considering points above, because right now if you failed with some build steps and try to run original command from source, without deleting build directory: `mkdir build && cd build` it will fail mkdir with error and will fail cd, therefore...Everything will be bad :laughing: 

This would be safer solution (or even just removing build directory prior cd to avoid possible conflicts?)
```
#!/bin/sh

if [ ! -d "build" ];
then
    mkdir build
fi

cd build

```

______

> Because I really see value in bringing the average user into contact with something like build instructions. Especially when it's just a couple commands.
Commands the average user will most certainly encounter again and again when trying to install software from source.

Here i agree, this is very valid point in general...I just see such small automation as time-saver, but again i have some experience and will to check script prior running :laughing: 

> If we really want to automate the install, then creating distribution packes would be the actual solution, but that's a whole another challange that's way out of question for now.

Yeah...This is "right way", but not fun. Maybe it will be necessary because of stuff like migrations of QT, but that's for the future if problems will arise :smiley: 


P.S. Feel free to close this of course :smiley:

**Comment by Goli4thus** [comment]
Yes, checking a script made by someone else before running it is good practice, but, once again, most likely not something that the average user will ever consider.

I agree, automation for time saving purposes has value.
But I don't think this is a case which will happen often for a user that might just be interested in github releases once on a while.
